
DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    UUID VARCHAR(200) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    USERNAME VARCHAR(30) UNIQUE NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL ,
    PASSWORD VARCHAR(255) NOT NULL,
    SALT VARCHAR(200) NOT NULL,
    COUNTRY VARCHAR(30),
    CONTACT_NUMBER VARCHAR(30)
);

INSERT INTO USERS(ID, UUID, FIRST_NAME, LAST_NAME, USERNAME, EMAIL, PASSWORD, SALT, COUNTRY, CONTACT_NUMBER)
	VALUES (101,'rdtrdtdyt','Palash','Tripathi','palash','p@upgrad.com','507FF5FED1CAC746','8Xt6jxoCI3MWsVaKY/1ySAp2qzlb2Z7P89+vDrb1o6U=', 'India' , '1222333333' );

DROP TABLE IF EXISTS USER_AUTH CASCADE;
CREATE TABLE IF NOT EXISTS USER_AUTH(
	ID BIGSERIAL PRIMARY KEY,
	UUID VARCHAR(200) NOT NULL,
	USER_ID INTEGER NOT NULL,
	ACCESS_TOKEN VARCHAR(500) NOT NULL,
	EXPIRES_AT TIMESTAMP NOT NULL,
	LOGIN_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LOGOUT_AT TIMESTAMP NULL
);

ALTER TABLE USER_AUTH ADD CONSTRAINT FK_USER_AUTH_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ;


DROP TABLE IF EXISTS POST CASCADE;
CREATE TABLE IF NOT EXISTS POST(
    ID SERIAL,
    UUID VARCHAR(200) NOT NULL,
    USER_ID INTEGER NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    BODY VARCHAR(2500) NOT NULL,
    LIKES VARCHAR(500) NOT NULL,
    DATE TIMESTAMP NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);


DROP TABLE IF EXISTS COMMENT CASCADE;
CREATE TABLE IF NOT EXISTS COMMENT(
    ID SERIAL,
    UUID VARCHAR(200) NOT NULL,
    USER_ID INTEGER NOT NULL,
    POST_ID INTEGER NOT NULL ,
    COMMENT VARCHAR(255) NOT NULL,
    DATE TIMESTAMP NOT NULL ,

    PRIMARY KEY(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(ID) ON DELETE CASCADE
);



